apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitme-deployment
  namespace: fitmeapp
  labels:
    job: fitme
    app: fitme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitme
  template:
    metadata:
      labels:
        app: fitme
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: fitme
          image: a11199/fit-me:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
            - containerPort: 8001
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST_AUTH_METHOD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_HOST_AUTH_METHOD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PORT
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: simplest-collector.monitoring.svc.cluster.local:4317
              #value: tempo.monitoring.svc.cluster.local:4317
      volumes:
        - name: fitme-volume
          hostPath:
            path: /tmp/data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: fitme
  namespace: fitmeapp
  labels:
    job: grpc-api
    app: fitme
spec:
  type: NodePort
  selector:
    app: fitme
  ports:
    - name: grpc
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30102
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30103
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fitme-deployment-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - fitmeapp
  selector:
    matchLabels:
      app: fitme
