apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fitme-deployment-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - fitmeapp
  selector:
    matchLabels:
      app: fitme
